server:
  port: 9002
spring:
  application:
    name: nacos-provider-payment
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'